'use client'

import { useState, useEffect } from 'react'
import { useLanguageStore } from '@/store/language-store'
import { translations, TranslationKey } from '@/lib/translations'

export function useTranslation() {
    const [mounted, setMounted] = useState(false)
    const lang = useLanguageStore((s) => s.lang)

    useEffect(() => {
        setMounted(true)
    }, [])

    const t = (key: TranslationKey): string => {
        // During SSR or until hydration is complete, always use Bengali ('bn')
        // to match the initial HTML generated by the server.
        const currentLang = mounted ? lang : 'bn'
        return translations[currentLang][key] ?? translations.bn[key] ?? key
    }

    return { t, lang: mounted ? lang : 'bn', isHydrated: mounted }
}
